apiVersion: v1
kind: Component
name: mjh
type: Service

build:
    buildPreset: Docker
    # 注意：这里我们只写文件名，这是最标准的写法
    dockerfilePath: Dockerfile

endpoints:
    - name: mjh-api
      port: 8080
      type: REST
      networkVisibility: Public
      context: /
